# Fuzzing Seed Blueprint JSON으로부터 "fuzzer_{num}_impacket.py" 생성
import json
import re
from openai import OpenAI

client = OpenAI()

def extract_code_from_response(text):
    """LLM 응답에서 Python 코드 블록만 추출"""
    match = re.search(r"```(?:python)?\s*(.*?)\s*```", text, re.DOTALL)
    if match:
        return match.group(1)
    return text

def generate_impacket_script(blueprint_file, output_script):
    # 1. Load Blueprint
    with open(blueprint_file, 'r', encoding='utf-8') as f:
        blueprint = json.load(f)

    target_func = blueprint.get("target_function", "Unknown")
    
    print(f"[+] Phase 4: Translating Blueprint to Impacket Code...")
    print(f"    - Target: {target_func}")
    print(f"    - Input: {blueprint_file}")

    # 2. Construct the "Developer" Prompt
    # 이 프롬프트가 '헤더 누락'과 '컨텍스트 누락'을 자동으로 보정합니다.
    prompt = f"""
    Role: Senior Python Developer specialized in Network Protocol Fuzzing & Impacket.

    Task:
    Convert the provided "Seed Blueprint JSON" into a working Python script
    that generates **valid, protocol-compliant raw packet payloads** suitable for offline fuzzing seed generation.

    The goal is to construct the full application-layer payload (e.g., NetBIOS Header + Protocol Header + Body) purely in memory and print the output.
    **DO NOT establish any network connections.**

    ---

    [Input Blueprint]
    {json.dumps(blueprint, indent=2)}

    ---

    [Core Requirements]

    1. Protocol Mapping
    - Each entry in `traffic_sequence` represents a protocol packet.
    - You MUST map each packet to an appropriate Impacket class when available.
    - If no suitable class exists, construct the packet manually using `struct.pack`.

    2. Full Packet Encapsulation (Framing)
    - The JSON defines logical packet fields. You MUST encapsulate them with the necessary transport framing required for the kernel driver to parse it.
    - **Example:** If the protocol typically runs over TCP port 445, you must prepend the **NetBIOS Session Service (NBSS) header** (or equivalent length header) before the protocol header.
    - The output must be the **exact byte sequence** that would be written to the TCP socket buffer.

    3. Offline State Simulation
    - Since there is no live server to respond, you cannot receive Session IDs, Tree IDs, or File IDs.
    - You MUST **mock** these stateful values.
    - Use consistent placeholders (e.g., `SessionID=0x11223344`) across the sequence to ensure logical continuity within the generated seed.
    - Assume all "requests" would theoretically succeed.

    4. Output Format
    - Do NOT use `socket` or `connect`.
    - Instead of sending, the script must **print the final generated bytes** for each packet in the sequence.
    - Format: Print the Packet Name followed by its **Hexdump** representation.

    ---

    [Output Code Structure]

    - Import required modules (`struct`, `impacket`, `binascii`, etc.)
    - One function per packet builder:
    - `build_<packet_name>() -> bytes` (Returns the full frame including NBSS/Framing)
    - A main execution block:
    - Iterate through the blueprint sequence.
    - Call build functions.
    - Print the result in the following format:
        `[+] <PacketName>: <HexString>`

    ---

    [STRICT OUTPUT RULE]
    OUTPUT ONLY THE PYTHON CODE.
    NO EXPLANATIONS.
    NO COMMENTS OUTSIDE THE CODE.
    """


    # 3. Request Code Generation
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are an expert Python network programmer. Write production-ready Impacket code."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.0
        )
        
        code = extract_code_from_response(response.choices[0].message.content)
        
        with open(output_script, 'w', encoding='utf-8') as f:
            f.write(code)
            
        print(f"    -> Successfully generated: {output_script}")
        print(f"    -> Usage: python {output_script} <target_ip>")
        
    except Exception as e:
        print(f"[-] Code Generation Failed: {e}")

# ==============================================================================
if __name__ == "__main__":
    # 이전 단계에서 생성된 JSON 파일명
    num = "0796"
    blueprint_file = f"fuzz_seed_blueprint_{num}.json" 
    # 생성할 파이썬 스크립트명
    output_py = f"fuzzer_{num}_impacket.py"

    generate_impacket_script(blueprint_file, output_py)